---
title: "学习 Emacs 第一天"
date: 2022-05-03T13:57:08+08:00
draft: false
---

这是一个 Emacs 的学习笔记，希望自己可以通过写这个博客记录自己学习 Emacs 的过程。由于我以前没有写过任何的博客，希望自己能通过这次学习 Emacs 的机会开始我的博客。其实我是一个没什么恒心的人，对自己的要求也没有那么高，这个博客有可能写不了多少就停止更新了。为了不影响那些想继续学习下去的人，我会把我学习过程中用到的资料都放在本文的最后，你可以通过这些学习资料继续学习下去，祝你能熟练掌握  Emacs ，成为一个高手。

* 为什么要学习 Emacs

我学习 Emacs 的原因首先是为了装X，这是不得不承认的事实，我并不是一个爱钻研的人，学习 Emacs 是一个很装X的事情。

Emacs 是一个我一直知道却一点也不会的东西，在学习 Vim 的过程中就知道了 Emacs 的存在。可是我一直以来就没有相关学习它，因为我觉得学习 Vim 就够为难我了，我实在没有学习 Emacs 的勇气。

通过一个播客节目重新了解到了 Emacs 相关的一些知识，介绍了许多 Emacs 的学习方法和学习资料。

我实在不喜欢 Vim 需要退出编辑模式才能移动光标（我对Vim 的了解很少，只是用来修改一些服务器上的配置文件）。

不管怎样也要会正确的退出 Emacs 吧。

* 安装 Emacs

其实安装 Emacs 很简单，不论是window系统还是Linux系统或Mac系统都可以从官网下载安装包。如果你安装都搞不定的话，你还是把这个页面关了吧，Emacs 真的不适合你。安装时最好选择一个比较新的版本。

** Windows 安装

从官网把安装包下载下来，找一个合适的目录把下载的压缩包解压出来就可以了。然后你就可以在 bin 目录下找到 runemacs.exe 运行就可以。运行这个命令会再桌面上创建一个快捷方式，你可以通过双击快捷方式启动。你还可以在 bin 目录下找到一个 addpm.exe 应用程序，执行这个程序会将 Emacs 添加到你的开始菜单中，你就可以从开始菜单中启动 Emacs 了。

** Mac 安装

直接打开终端，再终端中输入下面的命令并执行就可以了（我没有Mac电脑，没有测试过，希望有人赞助我一个 Mac 电脑我测试一下）。
#+BEGIN_SRC bash
brew install emacs --with-cocoa
#+END_SRC

** Linux 安装
由于 Linux 有很多的发行版本，不同的发行版的安装方式不太相同，我就不一一介绍了，你连 Linux 系统都装好了，安装 Emacs 一定难不倒你，祝你能安装成功。

* 退出 Emacs

本文最重要的内容来了，如何退出 Emacs 呢？其实这是一个很简单。首先不要在 Emacs 中乱按。你是不可能试出来的。

退出的命令是先按Ctrl + x然后再按 Ctrl + c就可以了，如何你这么操作还是不能退出，很有可能是之前你按了其他快捷键，这时你要先退出上一个没有完成的命令，方法是先按 Ctrl + g，可以多按几次，直到程序左下角显示 Quit 为止。然后再输入退出的命令就可以正常退出了。

如果你用 Emacs 打开了一些文件并修改一些内容，退出的时候会提示你保存修改内容，你想要保存内容的话就直接输入 y就可以了，不想保存的话输入 n，这时还是无法退出，再输入no就可以了。

这里再介绍一下保存文件的命令，先输入Ctrl + x，再输入Ctrl + s就可以了。

* 学习资料

Emacs 官网: http://www.gnu.org/software/emacs/

EmacsTalk 播客: https://emacstalk.github.io/

一年成为 Emacs 高手: https://blog.csdn.net/redguardtoo/article/details/7222501/

子龙山人视频资料: https://space.bilibili.com/292659700

Learning GNU Emacs: https://pan.baidu.com/s/1nwsbAZJ
